### ISSUE TITLE
AttributeError from /Lesson-3/20_JSON-Solution/

### ISSUE THREAD

**Issue by Shehab-Muhammad** [lobrown/Full-Stack-Foundations#64]
I got this error

> Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/web_server/webbyflask.py", line 18, in restaurantMenuJSON
    return item.serialize
AttributeError: 'MenuItem' object has no attribute 'serialize'

this my webbyflask.py

`from flask import Flask, render_template, request, url_for, redirect, flash, jsonify
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from database_setup import Base, Restaurant, MenuItem
from flask.templating import render_template
app = Flask(__name__)

engine = create_engine('sqlite:///restaurantmenu.db')
Base.metadata.bind = engine

DBSession = sessionmaker(bind=engine)
session = DBSession()

@app.route('/restaurants/<int:restaurant_id>/menu/<int:menu_id>/JSON')
def restaurantMenuJSON(restaurant_id, menu_id):
    item = session.query(MenuItem).filter_by(id = menu_id).one()
    return item.serialize`

and this is my database_setup.py

`import sys
import os
from sqlalchemy import Column, ForeignKey, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy import create_engine

Base = declarative_base()

class Restaurant(Base):
    __tablename__ = 'restaurant'
    name = Column(String(80), nullable = False)
    id = Column(Integer, primary_key = True)

class MenuItem(Base):
    __tablename__ = 'menu_item'
    
    name = Column(String(80), nullable = False)
    id = Column(Integer, primary_key = True)
    course = Column(String(250))
    description = Column(String(250))
    price = Column(String(8))
    restaurant_id = Column(Integer, ForeignKey('restaurant.id'))
    restaurant = relationship(Restaurant)
    
    @property
    def serialize(self):
        return {
            'name': self.name,
            'description': self.description,
            'id': self.id,
            'price': self.price,
            'course': self.course,
        }`

**Comment by tomdecort** [comment]
Hi,

I get the same error after I join tables. So how do you join tables and return the result in JSON?
`class JobContexts(db.Model):
    __tablename__ = 'job_contexts'
    __table_args__ = {'schema':'config'}
    job_context_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    execution_order = db.Column(db.Integer)

    def __init__(self, job_context_id, name, execution_order):
        self.job_context_id = job_context_id
        self.name = name
        self.execution_order = execution_order

    @property
    def json(self):
        return to_json(self, self.__class__)

    @property
    def serialize(self):
        """Return object data in easily serializable format"""
        return {
            'job_context_id'  : self.job_context_id,
            'name'            : self.name,
            'execution_order' : self.execution_order
        }

class Jobs(db.Model):
    __tablename__ = 'jobs'
    __table_args__ = {'schema':'config'}
    job_id = db.Column(db.Integer, primary_key=True)
    job_name = db.Column(db.String, nullable=False)
    job_context_id = db.Column(db.Integer, db.ForeignKey('JobContexts.job_context_id'))
    execution_order = db.Column(db.Integer)
    active = db.Column(db.Boolean)
    depending_of_jobs = db.Column(db.Integer)

    def __init__(self, job_id, job_name, job_context_id, execution_order, active, depending_of_jobs):
        self.job_id = job_id
        self.job_name = job_name
        self.job_context_id = job_context_id
        self.execution_order = execution_order
        self.active = active
        self.depending_of_jobs = depending_of_jobs

    @property
    def json(self):
        return to_json(self, self.__class__)

    @property
    def serialize(self):
       """Return object data in easily serializable format"""
       return {
           'job_id'            : self.job_id,
           'job_name'          : self.job_name,
           'job_context_id'    : self.job_context_id,
           'execution_order'   : self.execution_order,
           'depending_of_jobs' : self.depending_of_jobs
       }
`

and 

`def getAllJobs():
    #return jsonify(json_list = [i.serialize for i in jobs.query.all()]) ##> works fine!
    all_jobs = Jobs.query.join(JobContexts, Jobs.job_context_id == JobContexts.job_context_id).add_columns(JobContexts.name).all()
    return jsonify([i.serialize for i in all_jobs])`

Anyone knows about good documentation about flask_sqlalchemy providing more info on how to join tables etc.?

Cheers,
Tom

**Comment by VarunAdithya** [comment]
return jsonify(Menu_List =[i.serialize for i in Menu_Item])

**Comment by ppingpping** [comment]
> I got this error
> 
> > Traceback (most recent call last):
> > File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in **call**
> > return self.wsgi_app(environ, start_response)
> > File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
> > response = self.make_response(self.handle_exception(e))
> > File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
> > reraise(exc_type, exc_value, tb)
> > File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
> > response = self.full_dispatch_request()
> > File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
> > rv = self.handle_user_exception(e)
> > File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
> > reraise(exc_type, exc_value, tb)
> > File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
> > rv = self.dispatch_request()
> > File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
> > return self.view_functions[rule.endpoint](**req.view_args)
> > File "/vagrant/web_server/webbyflask.py", line 18, in restaurantMenuJSON
> > return item.serialize
> > AttributeError: 'MenuItem' object has no attribute 'serialize'
> 
> this my webbyflask.py
> 
> ```
> from flask import Flask, render_template, request, url_for, redirect, flash, jsonify
> from sqlalchemy import create_engine
> from sqlalchemy.orm import sessionmaker
> from database_setup import Base, Restaurant, MenuItem
> from flask.templating import render_template
> app = Flask(__name__)
> 
> 
> engine = create_engine('sqlite:///restaurantmenu.db')
> Base.metadata.bind = engine
> 
> DBSession = sessionmaker(bind=engine)
> session = DBSession()
> 
> @app.route('/restaurants/<int:restaurant_id>/menu/<int:menu_id>/JSON')
> def restaurantMenuJSON(restaurant_id, menu_id):
>     item = session.query(MenuItem).filter_by(id = menu_id).one()
>     return item.serialize
> ```
> 
> and this is my database_setup.py
> 
> ```
> import sys
> import os
> from sqlalchemy import Column, ForeignKey, Integer, String
> from sqlalchemy.ext.declarative import declarative_base
> from sqlalchemy.orm import relationship
> from sqlalchemy import create_engine
> 
> Base = declarative_base()
> 
> class Restaurant(Base):
>     __tablename__ = 'restaurant'
>     name = Column(String(80), nullable = False)
>     id = Column(Integer, primary_key = True)
> 
> class MenuItem(Base):
>     __tablename__ = 'menu_item'
> 
>     name = Column(String(80), nullable = False)
>     id = Column(Integer, primary_key = True)
>     course = Column(String(250))
>     description = Column(String(250))
>     price = Column(String(8))
>     restaurant_id = Column(Integer, ForeignKey('restaurant.id'))
>     restaurant = relationship(Restaurant)
> 
>     @property
>     def serialize(self):
>         return {
>             'name': self.name,
>             'description': self.description,
>             'id': self.id,
>             'price': self.price,
>             'course': self.course,
>         }
> ```

Hvuhionpm
